### ISSUE TITLE
Motion Vectors

### ISSUE THREAD

**Issue by danielzeller** [keijiro/NoiseBall6#1]
Hi Keijiro
Love checking out whenever there is a new NoiseBall example! :)  
Any chance you could make the example work with motion vectors?

**Comment by keijiro** [comment]
The short answer is no.

Supporting motion vectors with vertex animation is quite tricky. That's a nice topic as an advanced use case, but it wouldn't be in the scope of this simple API example.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by danielzeller** [comment]
Cool, yeah I would love to see a more advanced example with motion vector support. I think a lot of people have benefited from the other examples of custom motion vector that you have made. But those seem only to work with the built in pipeline. Getting it to work with HDRP seems a lot more difficult, the only very hacky solution I've come across is this super hacky reflection based one by Nexusmaster here: https://forum.unity.com/threads/enabling-motion-vector-pass-for-drawprocedural.939452/
